name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - dev  # 或你的預設分支

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "20"

    - name: Install dependencies
      run: npm install

    - name: Generate hexo static files
      run: npx hexo generate

    - name: Deploy to GitHub Pages
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_REPOSITORY: princend/hexo-test
        BRANCH: main
        PUBLISH_DIR: ./public
        USER_NAME: princend
        USER_EMAIL: waxdji3g4y3c04@gmail.com
      run: |
        git config --global user.name "${USER_NAME}"
        git config --global user.email "${USER_EMAIL}"
        npx hexo-deployer-git --repo=https://x-access-token:${PERSONAL_TOKEN}@github.com/${PUBLISH_REPOSITORY}.git --branch=${BRANCH} --message="Site updated: $(date '+%Y-%m-%d %H:%M:%S')" --dir=${PUBLISH_DIR}
